name: phpunit
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0", "8.1", "8.2", "8.3" ]
                symfony: [ "4.0", "5.0", "6.0", "7.0" ]
                exclude:
                    - php: "8.1"
                      symfony: "4.0"
                      
                    - php: "8.2"
                      symfony: "4.0"
                      
                    - php: "8.3"
                      symfony: "4.0"
                      
                    - php: "8.2"
                      symfony: "5.0"
                      
                    - php: "8.3"
                      symfony: "5.0"
                      
                    - php: "7.3"
                      symfony: "6.0"
                      
                    - php: "7.4"
                      symfony: "6.0"
                      
                    - php: "8.0"
                      symfony: "6.0"
                      
                    - php: "7.3"
                      symfony: "7.0"
                      
                    - php: "7.4"
                      symfony: "7.0"
                      
                    - php: "8.0"
                      symfony: "7.0"
                      
                    - php: "8.1"
                      symfony: "7.0"

        name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, bcmath
                    coverage: none

            -   name: Install dependencies
                run: composer require symfony/http-foundation:^${{ matrix.symfony }} --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
